
server:
  port: 8082
  shutdown: graceful
  maxHttpHeaderSize: 20480
  undertow:
    bufferSize: 1024
    maxHttpPostSize: 22020096
    threads:
      io: 16
      worker: 128
  forward-headers-strategy: framework

spring:
  application:
    name: ${APP_NAME:performance}
  threads:
    virtual:
      enabled: true

# forbidden all log output
#logging.level.root: OFF